layout_spectrum: 0.2309020403359491
typography_spectrum: 0.6018858649666504
color:
  brandStrength: 0.8173941639546158
  lightness: 0.21081800558318448
  saturation: 0.6652041815326429
  rhythmicContrast: 0.5446793742907593
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
github: true
author:
  name: Laura Kelly
  email: laura@laurakelly.com.au
  url: 'http://laurakelly.com.au'
name: Laura Kelly
url: 'http://laurakelly.com.au/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: Laura Kelly
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fdy_JEytfspU%3Fstart%3D20%26feature%3Doembed%26start%3D20&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Ddy_JEytfspU&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fdy_JEytfspU%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Chad Mercree
          url: 'https://www.youtube.com/channel/UCgjkERuhWDkiZYuumgY-7KA'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - alpaca
        - alpaca ranch
        - alpaca as pets
        - alpaca animal
        - alpaca pets
        - alpaca animal totem
        - alpaca baby
        - suri alpaca fur
        - alpaca images
        - alpaca noise
        - what does a...
      description: >-
        Enjoy this relaxing video meditation with the sounds of nature and
        gentle suri alpacas whose spirit animal totem essence is love. It's like
        putting on a comfortingly warm pair of alpaca socks made of premium
        alpaca wool. You can feel like you are relaxing on a tranquil alpaca
        farm listening to their soothing sounds as you knit with alpaca yarn.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=dy_JEytfspU&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=dy_JEytfspU&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=dy_JEytfspU&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=dy_JEytfspU&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=dy_JEytfspU&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=dy_JEytfspU'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=dy_JEytfspU
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=dy_JEytfspU
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/dy_JEytfspU?t=20s'
      title: Alpaca Humming
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: contact
    url: 'mailto:laura@laurakelly.com.au'
    label: Email
  - type: contact
    url: 'tel:0401559335'
    label: Call
analytics:
  google: UA-70092553-1
