layout_spectrum: 0.2309020403359491
typography_spectrum: 0.6018858649666504
color:
  brandStrength: 0.8173941639546158
  lightness: 0.21081800558318448
  saturation: 0.6652041815326429
  rhythmicContrast: 0.5446793742907593
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
github: true
author:
  name: Laura Kelly
  email: laura@laurakelly.com.au
  url: 'http://laurakelly.com.au'
name: Laura Kelly
url: 'http://laurakelly.com.au/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: Laura Kelly
content: []
description: laurakelly.com.au
purpose:
  - type: contact
    url: 'mailto:laura@laurakelly.com.au'
    label: Email
  - type: contact
    url: 'tel:0401559335'
    label: Call
analytics:
  google: UA-70092553-1
