layout_spectrum: 0.2309020403359491
typography_spectrum: 0.6018858649666504
color:
  brandStrength: 0.8173941639546158
  lightness: 0.21081800558318448
  saturation: 0.6652041815326429
  rhythmicContrast: 0.5446793742907593
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
github: true
author:
  name: Laura Kelly
  email: laura@laurakelly.com.au
  url: 'http://laurakelly.com.au'
name: Laura Kelly
url: 'http://laurakelly.com.au/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: Laura Kelly
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: article
    html: >-
      <article><h1>No Cookies | The Mercury</h1><p>There is a specific issue
      with the Facebook in-app browser intermittently making requests to
      websites without cookies that had previously been set. This appears to be
      a defect in the browser which should be addressed soon. The simplest
      approach to avoid this problem is to continue to use the Facebook app but
      not use the in-app browser.</p></article>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: >-
        http://www.themercury.com.au/lifestyle/environment-tasmania-calls-on-wwf-to-cut-ties-with-salmon-farming-giant-tassal/news-story/87220c553bfe3107c3f2a5d76f7a288d
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      title: No Cookies | The Mercury
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'http://www.themercury.com.au'
        name: Themercury
        favicon: >-
          https://secure.gravatar.com/blavatar/a2dca69b3a848c77a9d7ffa55925f70b?s=32
        domain: www.themercury.com.au
      description: >-
        There is a specific issue with the Facebook in-app browser
        intermittently making requests to websites without cookies that had
        previously been set. This appears to be a defect in the browser which
        should be addressed soon. The simplest approach to avoid this problem is
        to continue to use the Facebook app but not use the in-app browser.
    title: No Cookies | The Mercury
    caption: >-
      There is a specific issue with the Facebook in-app browser intermittently
      making requests to websites without cookies that had previously been set.
      This appears to be a defect in the browser which should be addressed soon.
      The simplest approach to avoid this problem is to continue to use the
      Facebook app but not use the in-app browser.
    text: !<tag:yaml.org,2002:js/undefined> ''
description: laurakelly.com.au
purpose:
  - type: contact
    url: 'mailto:laura@laurakelly.com.au'
    label: Email me
analytics:
  google: UA-70092553-1
